version: '3'

services:
  insta-go:
    container_name: insta_m_go_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    working_dir: /app
    ports:
      - "5002:5002"
    networks:
      - go-network

networks:
  go-network:
    name: instabug_task
    external: true